### ISSUE TITLE
Add Base URL support

### ISSUE THREAD

**Issue by VectorZhao** [chapyter/chapyter#21]
Please add base url support for using openai of Azure. 
```
OPENAI_BASE_URL=xxx
OPENAI_API_KEY=sk-xxxx
OPENAI_ORGANIZATION=org-xxxx
```
Of course, direct support for Azure is also possible.
https://learn.microsoft.com/en-us/azure/cognitive-services/openai/quickstart?tabs=command-line&pivots=programming-language-python

**Comment by lolipopshock** [comment]
Thanks! Will get this fixed very soon!

**Comment by lolipopshock** [comment]
See #31

**Comment by lolipopshock** [comment]
Should be good after v0.3.0 release.
