### ISSUE TITLE
Error communicating with OpenAI when use proxy.

### ISSUE THREAD

**Issue by wanggk114** [chapyter/chapyter#22]
Why can’t the server be accessed using a proxy?

The exception msg:
![image](https://github.com/chapyter/chapyter/assets/32860686/745a809b-de4a-4e11-b5f3-4c8c79e95614)

The https proxy has already been set in the proxy settings, as follows:
![image](https://github.com/chapyter/chapyter/assets/32860686/065075ea-563b-4bdf-90af-a8aa8249aabe)

Other test programs can responsed normally by directly calling the API using request, as follows：
![image](https://github.com/chapyter/chapyter/assets/32860686/4aebeb26-d145-4769-b4b8-59a45c6bde77)

Can anyone help solve this problem? Thanks so much~~

**Comment by hzhx7707** [comment]
同样遇到了这个问题

**Comment by hzhx7707** [comment]
change the openai base_url in the .env
OPENAI_API_BASE="https://api.openai-proxy.com/v1"

**Comment by Bishop-Cui** [comment]
@wanggk114 Hi, have you solved it?

**Comment by wanggk114** [comment]
> change the openai base_url in the .env OPENAI_API_BASE="https://api.openai-proxy.com/v1"

It's Work!!! thanks

**Comment by wanggk114** [comment]
> @wanggk114 Hi, have you solved it?
