### ISSUE TITLE
Feature Request: Support an environment variable for picking OpenAI model

### ISSUE THREAD

**Issue by randerzander** [chapyter/chapyter#26]
Support setting an environment variable for specifying the OpenAI model name to use.

If I want to save pennies by using gpt 3.5 instead of 4, it'd be nice not to have to include "-m gpt-3.5-turbo" in every cell magic invocation.

**Comment by lolipopshock** [comment]
Thanks! Yes I am working on this feature, along with #5 #21

**Comment by lolipopshock** [comment]
see #31

**Comment by lolipopshock** [comment]
Should be good after the v0.3.0 release.
