### ISSUE TITLE
Why is %load_ext necessary?

### ISSUE THREAD

**Issue by orome** [chapyter/chapyter#29]
This may be a Python or Jupyter question but I've never encountered this before with an extension so just asking here in case it's related. Why do I need `%load_ext chapyter`? I've used lots of extensions and have never encountered the need for `%load_ext` before. Most (all) load automatically just by being installed with `pip`.

**Comment by lolipopshock** [comment]
Yes I figured out to remove this command; it will come with the next release

**Comment by lolipopshock** [comment]
See the notebook in #31
