### ISSUE TITLE
Does not execute automatically

### ISSUE THREAD

**Issue by VectorZhao** [chapyter/chapyter#33]
When I run the command `%%chat`, the generated code does not execute automatically.

**Comment by lolipopshock** [comment]
What is the version of the ipython kernel and Jupyter notebook you are using?

```
ipython --version
jupyter notebook --version
jupyter lab --version
```

**Comment by VectorZhao** [comment]
(base) C:\Users\10923>ipython --version
8.10.0

(base) C:\Users\10923>jupyter notebook --version
6.5.2

(base) C:\Users\10923>jupyter lab --version
3.6.5

**Comment by lolipopshock** [comment]
You might want to upgrade Jupyter lab to >=4.0 and this issue should be fixed.

**Comment by VectorZhao** [comment]
solved，thx
