### ISSUE TITLE
Uable to add use %chapyter openai_api_org  = 'value' 

### ISSUE THREAD

**Issue by aiyinyuedejustin** [chapyter/chapyter#36]
Hi there, I want to configure the chapyter. However, when I use %chapyter openai_api_org = 'org-myorg', it's said that:

UsageError: Invalid usage of the chapyter command: openai_api_org = 'org-PrhJLJTejKb36yGXRldiR9RT'. It supports the following usage:
- %chapyter
  print all the configurable parameters and its current value
- %chapyter <parameter_name>
  print the current value of the parameter
- %chapyter <parameter_name>=<value>
  set the value of the parameter

**Comment by lolipopshock** [comment]
Can u remove the space between the equal sign and try again?

**Comment by lolipopshock** [comment]
#38 is merged and this should be fixed in the next release
