### ISSUE TITLE
UsageError: Cell magic `%%chat` not found.

### ISSUE THREAD

**Issue by p971607** [chapyter/chapyter#40]
i run:
%%chat -m gpt-4-0613 
List all the files in the folder

but:
UsageError: Cell magic `%%chat` not found.

![bug1](https://github.com/chapyter/chapyter/assets/129634678/970049ee-3144-405b-a51e-0d3a9bb93b37)

**Comment by lolipopshock** [comment]
You might want to add `%load_ext chapyter` at the very beginning.
