### ISSUE TITLE
Environment variable OPEN_AI_KEY not found by 

### ISSUE THREAD

**Issue by Cortado-J** [chapyter/chapyter#42]
I'm running JupyterLab 4.0.4 on a Mac and trying to use Chapyter.
I have an environment variable OPEN_AI_KEY set and can check this by: echo $OPENAI_API_KEY

Chapyter is installed and in my first cell I have:
```
%load_ext chapyter
```

And then:

```
%%chat
add numbers from 1 to 10
```
I get this error:
`
assert openai.api_key is not None, "You must provide an OpenAI API key to use the OpenAI LLM. Either pass it in the constructor, set the OPENAI_API_KEY environment variable, or create the file ~/.openai_api_key with your key in it."
`

**Comment by lolipopshock** [comment]
Thanks! Can you try to print the value of the environment variable in the same Jupyter notebook as well? 
For example, 
after the `%%chat`  cell, you can try 
```python
import os 
print(os.environ['OPENAI_API_KEY'])
```

**Comment by Cortado-J** [comment]
Thanks!
I get:
```
---------------------------------------------------------------------------
KeyError                                  Traceback (most recent call last)
Cell In[6], line 2
      1 import os 
----> 2 print(os.environ['OPENAI_API_KEY'])

File ~/anaconda3/lib/python3.10/os.py:680, in _Environ.__getitem__(self, key)
    677     value = self._data[self.encodekey(key)]
    678 except KeyError:
    679     # raise KeyError with the original key value
--> 680     raise KeyError(key) from None
    681 return self.decodevalue(value)

KeyError: 'OPENAI_API_KEY'
```

which is indicating that the python instance is not seeing my environment variable but in terminal if I do:
`echo $OPENAI_API_KEY`
I get my key displayed.
I have put:
`export OPENAI_API_KEY="<my open ai key>"`
in my bash profile and run it.
So I'm baffled why Jupyter doesn't pick it up?

**Comment by jimwhite** [comment]
Setting environment variables for access within Jupyter depends on your OS and how you launch Jupyter.

A couple platform independent approaches are to:

# use .env file
%pip install python-dotenv
from dotenv import load_dotenv
load_dotenv()

# use getpass
import os
from getpass import getpass
os.environ["OPENAI_API_KEY"] = getpass()

# use magic
And of course there is the %env magic if you aren't trying to keep the key out of the notebook itself.
https://ipython.readthedocs.io/en/stable/interactive/magics.html#magic-env

**Comment by Cortado-J** [comment]
Thanks @jimwhite,
The getpass() method worked ok for me.
Thanks very much.
