### ISSUE TITLE
About <your-azure-openai-api-base>

### ISSUE THREAD

**Issue by 27182812** [chapyter/chapyter#44]
Can you tell me what <your-azure-openai-api-base> is in "%chapyter azure_openai_api_base="https://<your-azure-openai-api-base>.openai.azure.com/" ？I can't find the introduction for it.

**Comment by lolipopshock** [comment]
https://learn.microsoft.com/en-us/azure/ai-services/openai/reference  -- see the `**YOUR_RESOURCE_NAME**.openai.azure.com`

**Comment by 27182812** [comment]
So does this mean I need to request Access to Azure OpenAI Service？

**Comment by lolipopshock** [comment]
> So does this mean I need to request Access to Azure OpenAI Service？

yes

**Comment by 27182812** [comment]
Thank you for your reply.
